# Project: Json
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o cJSON.o
LINKOBJ  = main.o cJSON.o
LIBS     = -L"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/lib" -L"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/include" -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/include" -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/ruanjian/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Json.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

cJSON.o: cJSON.c
	$(CC) -c cJSON.c -o cJSON.o $(CFLAGS)
